
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS phone;

--Create 'customer' table and provisioning test data
CREATE TABLE customer (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(50) NOT NULL,
  email VARCHAR(50)
);

--Mock data generated from https://www.mockaroo.com/
insert into customer (name, address, email) values ('Yolande Youde', '60 Pond Plaza', 'yyoude0@ustream.tv');
insert into customer (name, address, email) values ('Billie Lindro', '9 Forest Plaza', 'blindro1@oracle.com');
insert into customer (name, address, email) values ('Aldridge Bissell', '1 Northwestern Hill', 'abissell2@pbs.org');
insert into customer (name, address, email) values ('Verge McClinton', '83607 Canary Avenue', 'vmcclinton3@hatena.ne.jp');
insert into customer (name, address, email) values ('Della Andrzej', '0 Ludington Trail', 'dandrzej4@infoseek.co.jp');
insert into customer (name, address, email) values ('Lenna Guinn', '54447 Harbort Terrace', 'lguinn5@ucla.edu');
insert into customer (name, address, email) values ('Sabine Ledes', '8 Village Plaza', 'sledes6@slashdot.org');
insert into customer (name, address, email) values ('Kirsteni Gregan', '75 Schmedeman Drive', 'kgregan7@amazon.com');
insert into customer (name, address, email) values ('Emmott Priddie', '0683 Magdeline Park', 'epriddie8@simplemachines.org');
insert into customer (name, address, email) values ('Abie Fleetwood', '4 Daystar Terrace', 'afleetwood9@tumblr.com');
insert into customer (name, address, email) values ('Eddy Lathy', '6 Schurz Circle', 'elathya@omniture.com');
insert into customer (name, address, email) values ('Babette Mergue', '5322 Fallview Road', 'bmergueb@github.com');
insert into customer (name, address, email) values ('Hube Ouldcott', '7 Leroy Pass', 'houldcottc@dailymail.co.uk');
insert into customer (name, address, email) values ('Carmon Pulley', '43040 Cascade Drive', 'cpulleyd@vk.com');
insert into customer (name, address, email) values ('Emmalynn Kempster', '4944 Harper Pass', 'ekempstere@java.com');
insert into customer (name, address, email) values ('Cesar Winterscale', '788 Magdeline Way', 'cwinterscalef@oakley.com');
insert into customer (name, address, email) values ('Jerald Erni', '07354 Fremont Crossing', 'jernig@example.com');
insert into customer (name, address, email) values ('Claiborn McConnachie', '22025 Del Mar Junction', 'cmcconnachieh@noaa.gov');
insert into customer (name, address, email) values ('Kathi Hawford', '966 Fremont Way', 'khawfordi@yelp.com');
insert into customer (name, address, email) values ('Eberhard Lutzmann', '217 Melrose Junction', 'elutzmannj@edublogs.org');
insert into customer (name, address, email) values ('Jenny Feldberger', '24126 Cottonwood Parkway', 'jfeldbergerk@amazon.co.jp');
insert into customer (name, address, email) values ('Orland Davidde', '19768 Sutherland Plaza', 'odaviddel@vistaprint.com');
insert into customer (name, address, email) values ('Inessa Rumgay', '4 Clove Circle', 'irumgaym@w3.org');
insert into customer (name, address, email) values ('Jamill Beadel', '96834 Erie Parkway', 'jbeadeln@de.vu');
insert into customer (name, address, email) values ('Madelle Getcliffe', '13414 Westerfield Circle', 'mgetcliffeo@slideshare.net');
insert into customer (name, address, email) values ('Collie Awde', '98 Fieldstone Alley', 'cawdep@wsj.com');
insert into customer (name, address, email) values ('Merle MacDonald', '41050 Dakota Point', 'mmacdonaldq@tuttocitta.it');
insert into customer (name, address, email) values ('Austina Mussettini', '995 Washington Junction', 'amussettinir@psu.edu');
insert into customer (name, address, email) values ('Dawna Schiefersten', '72125 Bunker Hill Junction', 'dschieferstens@boston.com');
insert into customer (name, address, email) values ('Grete Keaveny', '88 Superior Park', 'gkeavenyt@zimbio.com');
insert into customer (name, address, email) values ('Kaleena Van Arsdale', '8 Kings Alley', 'kvanu@technorati.com');
insert into customer (name, address, email) values ('Doti Vaughn', '90 Vermont Avenue', 'dvaughnv@sciencedaily.com');
insert into customer (name, address, email) values ('Marylinda Ricart', '2 Trailsway Plaza', 'mricartw@ed.gov');
insert into customer (name, address, email) values ('Zeb Petworth', '08 Schiller Parkway', 'zpetworthx@tumblr.com');
insert into customer (name, address, email) values ('Edie Cockerill', '5 Hansons Trail', 'ecockerilly@cmu.edu');
insert into customer (name, address, email) values ('Hart Eberdt', '51 Alpine Avenue', 'heberdtz@goo.gl');
insert into customer (name, address, email) values ('Averil Doorbar', '53 Clyde Gallagher Trail', 'adoorbar10@ibm.com');
insert into customer (name, address, email) values ('Micki Evens', '95 Southridge Alley', 'mevens11@ezinearticles.com');
insert into customer (name, address, email) values ('Tymon Eason', '23 Sunnyside Street', 'teason12@myspace.com');
insert into customer (name, address, email) values ('Leeland Linnane', '0 Harper Park', 'llinnane13@ifeng.com');
insert into customer (name, address, email) values ('Alfonse Gartrell', '9828 Kropf Circle', 'agartrell14@51.la');
insert into customer (name, address, email) values ('Carl Holmyard', '6647 Summer Ridge Trail', 'cholmyard15@unicef.org');
insert into customer (name, address, email) values ('Clari Baumadier', '9 Morning Plaza', 'cbaumadier16@hostgator.com');
insert into customer (name, address, email) values ('Zackariah Filson', '430 Aberg Court', 'zfilson17@surveymonkey.com');
insert into customer (name, address, email) values ('Marjie McMichael', '69511 Hallows Trail', 'mmcmichael18@ask.com');
insert into customer (name, address, email) values ('Boone Watson', '90223 2nd Point', 'bwatson19@webeden.co.uk');
insert into customer (name, address, email) values ('Sasha Kiffe', '2541 Linden Alley', 'skiffe1a@google.com.hk');
insert into customer (name, address, email) values ('Myrtle Carrack', '653 La Follette Street', 'mcarrack1b@youtu.be');
insert into customer (name, address, email) values ('Alvan Ledwith', '49 Kennedy Way', 'aledwith1c@qq.com');
insert into customer (name, address, email) values ('Griffie Redbourn', '9 Homewood Street', 'gredbourn1d@gizmodo.com');
insert into customer (name, address, email) values ('Arley Strickland', '812 North Plaza', 'astrickland1e@economist.com');
insert into customer (name, address, email) values ('Van Moore', '13138 High Crossing Circle', 'vmoore1f@diigo.com');
insert into customer (name, address, email) values ('Jorrie Davana', '6 Becker Crossing', 'jdavana1g@vk.com');
insert into customer (name, address, email) values ('Tris Stockbridge', '28 Chinook Junction', 'tstockbridge1h@twitter.com');
insert into customer (name, address, email) values ('Michel Williscroft', '678 Sauthoff Road', 'mwilliscroft1i@whitehouse.gov');
insert into customer (name, address, email) values ('Lane Artis', '2843 Waywood Junction', 'lartis1j@msn.com');
insert into customer (name, address, email) values ('Allene Patis', '9 Jana Trail', 'apatis1k@dailymail.co.uk');
insert into customer (name, address, email) values ('Genia Eschelle', '11 Buena Vista Way', 'geschelle1l@imgur.com');
insert into customer (name, address, email) values ('Shaina Decent', '346 Duke Pass', 'sdecent1m@reddit.com');
insert into customer (name, address, email) values ('Krystalle Lippiello', '95 Rutledge Terrace', 'klippiello1n@earthlink.net');
insert into customer (name, address, email) values ('Hernando Voules', '370 Nelson Hill', 'hvoules1o@trellian.com');
insert into customer (name, address, email) values ('Sallee Hatherley', '29 Kennedy Road', 'shatherley1p@360.cn');
insert into customer (name, address, email) values ('Ilario Castanaga', '956 Havey Court', 'icastanaga1q@weather.com');
insert into customer (name, address, email) values ('Dolorita Roj', '88 Lawn Alley', 'droj1r@china.com.cn');
insert into customer (name, address, email) values ('Syman Gerner', '4 Lien Point', 'sgerner1s@dyndns.org');
insert into customer (name, address, email) values ('Celie Vile', '93 Dayton Street', 'cvile1t@phoca.cz');
insert into customer (name, address, email) values ('Elysia Giaomozzo', '9 Di Loreto Trail', 'egiaomozzo1u@ocn.ne.jp');
insert into customer (name, address, email) values ('Silvester Kernan', '519 Hazelcrest Trail', 'skernan1v@yandex.ru');
insert into customer (name, address, email) values ('Zane Wilcinskis', '86638 Oneill Circle', 'zwilcinskis1w@example.com');
insert into customer (name, address, email) values ('Gretchen Riddick', '8 Sycamore Junction', 'griddick1x@squidoo.com');
insert into customer (name, address, email) values ('Rafaelia Lillistone', '9 Bartelt Junction', 'rlillistone1y@tuttocitta.it');
insert into customer (name, address, email) values ('Nadeen Pigny', '332 Roxbury Parkway', 'npigny1z@networkadvertising.org');
insert into customer (name, address, email) values ('Nissa Cradoc', '9 Menomonie Pass', 'ncradoc20@symantec.com');
insert into customer (name, address, email) values ('Yevette Walrond', '37038 Towne Park', 'ywalrond21@rakuten.co.jp');
insert into customer (name, address, email) values ('Cinderella Foston', '17772 Sycamore Center', 'cfoston22@archive.org');
insert into customer (name, address, email) values ('Ari Ferrieroi', '8 Shoshone Crossing', 'aferrieroi23@flickr.com');
insert into customer (name, address, email) values ('Weylin Hellcat', '92 Lawn Plaza', 'whellcat24@xinhuanet.com');
insert into customer (name, address, email) values ('Blondelle Pickavant', '963 Old Gate Alley', 'bpickavant25@sogou.com');
insert into customer (name, address, email) values ('Sibyl Mack', '75228 Donald Court', 'smack26@xinhuanet.com');
insert into customer (name, address, email) values ('Alene Hynson', '60 Pawling Way', 'ahynson27@myspace.com');
insert into customer (name, address, email) values ('Artemis Bea', '12912 Mccormick Crossing', 'abea28@zimbio.com');
insert into customer (name, address, email) values ('Lucas Tabourin', '73730 Macpherson Way', 'ltabourin29@aboutads.info');
insert into customer (name, address, email) values ('David Arman', '6778 Mcbride Park', 'darman2a@nba.com');
insert into customer (name, address, email) values ('Benetta Lokier', '75 Raven Park', 'blokier2b@parallels.com');
insert into customer (name, address, email) values ('Annis Cordrey', '896 Cascade Court', 'acordrey2c@ed.gov');
insert into customer (name, address, email) values ('Florian Patron', '787 Prairie Rose Street', 'fpatron2d@springer.com');
insert into customer (name, address, email) values ('Salomon Abram', '9 Crest Line Parkway', 'sabram2e@nature.com');
insert into customer (name, address, email) values ('Lindsay Attenburrow', '15343 Pankratz Pass', 'lattenburrow2f@abc.net.au');
insert into customer (name, address, email) values ('Christean Gamage', '6359 Sachs Pass', 'cgamage2g@google.com.hk');
insert into customer (name, address, email) values ('Matilda Cholwell', '4 Knutson Circle', 'mcholwell2h@barnesandnoble.com');
insert into customer (name, address, email) values ('Vinita Bessey', '3 2nd Terrace', 'vbessey2i@gravatar.com');
insert into customer (name, address, email) values ('Maudie Rhydderch', '023 Logan Point', 'mrhydderch2j@omniture.com');
insert into customer (name, address, email) values ('Efrem Rispine', '94453 Westridge Alley', 'erispine2k@japanpost.jp');
insert into customer (name, address, email) values ('Gregorio Vankeev', '5760 Ludington Place', 'gvankeev2l@ed.gov');
insert into customer (name, address, email) values ('Ulrike Dallosso', '63 Nova Hill', 'udallosso2m@ebay.co.uk');
insert into customer (name, address, email) values ('Kettie Batalini', '59799 Sundown Street', 'kbatalini2n@ovh.net');
insert into customer (name, address, email) values ('Irvine Enrigo', '7374 Coolidge Avenue', 'ienrigo2o@globo.com');
insert into customer (name, address, email) values ('Casey Whether', '115 Burrows Hill', 'cwhether2p@hubpages.com');
insert into customer (name, address, email) values ('Tiphani Riddington', '3854 High Crossing Trail', 'triddington2q@discuz.net');
insert into customer (name, address, email) values ('Kimbell Kewley', '23676 Hayes Pass', 'kkewley2r@cbc.ca');

--Create 'phone' table and provisioning test data
CREATE TABLE phone (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  number VARCHAR(30) NOT NULL,
  customer_id VARCHAR(50) NOT NULL,
  active BOOLEAN NOT NULL
);

----Mock data generated from https://www.mockaroo.com/
insert into phone (number, customer_id, active) values ('040-315-0243', 78, false);
insert into phone (number, customer_id, active) values ('044-803-0327', 1, true);
insert into phone (number, customer_id, active) values ('049-060-7692', 29, true);
insert into phone (number, customer_id, active) values ('042-217-9683', 63, false);
insert into phone (number, customer_id, active) values ('045-616-4369', 98, false);
insert into phone (number, customer_id, active) values ('048-540-9980', 60, false);
insert into phone (number, customer_id, active) values ('040-730-5928', 55, true);
insert into phone (number, customer_id, active) values ('040-142-6304', 88, false);
insert into phone (number, customer_id, active) values ('048-120-5136', 21, true);
insert into phone (number, customer_id, active) values ('043-718-7164', 54, true);
insert into phone (number, customer_id, active) values ('043-825-5154', 74, false);
insert into phone (number, customer_id, active) values ('049-666-1338', 52, false);
insert into phone (number, customer_id, active) values ('047-403-0424', 62, false);
insert into phone (number, customer_id, active) values ('045-331-2190', 25, false);
insert into phone (number, customer_id, active) values ('040-557-1646', 43, true);
insert into phone (number, customer_id, active) values ('048-888-8889', 85, false);
insert into phone (number, customer_id, active) values ('043-819-1974', 15, false);
insert into phone (number, customer_id, active) values ('046-755-8172', 9, false);
insert into phone (number, customer_id, active) values ('045-633-6065', 66, false);
insert into phone (number, customer_id, active) values ('044-162-5658', 58, true);
insert into phone (number, customer_id, active) values ('043-666-1558', 31, true);
insert into phone (number, customer_id, active) values ('041-355-1193', 33, false);
insert into phone (number, customer_id, active) values ('041-465-8603', 5, true);
insert into phone (number, customer_id, active) values ('043-348-4809', 37, false);
insert into phone (number, customer_id, active) values ('047-196-8976', 22, false);
insert into phone (number, customer_id, active) values ('048-108-1944', 17, true);
insert into phone (number, customer_id, active) values ('046-680-3545', 99, false);
insert into phone (number, customer_id, active) values ('042-875-7893', 80, true);
insert into phone (number, customer_id, active) values ('046-107-4693', 48, true);
insert into phone (number, customer_id, active) values ('041-285-4015', 51, true);
insert into phone (number, customer_id, active) values ('049-289-4678', 95, false);
insert into phone (number, customer_id, active) values ('041-034-0935', 52, false);
insert into phone (number, customer_id, active) values ('045-719-6219', 16, false);
insert into phone (number, customer_id, active) values ('045-315-7987', 35, false);
insert into phone (number, customer_id, active) values ('044-196-4151', 10, false);
insert into phone (number, customer_id, active) values ('040-900-8016', 77, false);
insert into phone (number, customer_id, active) values ('048-034-4071', 20, false);
insert into phone (number, customer_id, active) values ('047-603-8369', 64, false);
insert into phone (number, customer_id, active) values ('049-048-9011', 68, false);
insert into phone (number, customer_id, active) values ('049-667-5911', 95, true);
insert into phone (number, customer_id, active) values ('045-977-1815', 22, false);
insert into phone (number, customer_id, active) values ('043-056-5314', 55, false);
insert into phone (number, customer_id, active) values ('041-499-9178', 39, false);
insert into phone (number, customer_id, active) values ('048-430-3796', 25, false);
insert into phone (number, customer_id, active) values ('043-071-9383', 86, true);
insert into phone (number, customer_id, active) values ('045-522-0973', 72, false);
insert into phone (number, customer_id, active) values ('046-597-4209', 69, false);
insert into phone (number, customer_id, active) values ('047-715-4348', 41, false);
insert into phone (number, customer_id, active) values ('040-024-9685', 64, true);
insert into phone (number, customer_id, active) values ('041-316-9606', 65, false);
insert into phone (number, customer_id, active) values ('046-588-2952', 23, true);
insert into phone (number, customer_id, active) values ('045-130-9984', 45, true);
insert into phone (number, customer_id, active) values ('049-799-5637', 16, false);
insert into phone (number, customer_id, active) values ('046-095-0172', 14, false);
insert into phone (number, customer_id, active) values ('043-805-5645', 87, false);
insert into phone (number, customer_id, active) values ('043-513-7923', 94, false);
insert into phone (number, customer_id, active) values ('041-002-8860', 64, true);
insert into phone (number, customer_id, active) values ('045-352-2615', 54, false);
insert into phone (number, customer_id, active) values ('045-954-4467', 36, false);
insert into phone (number, customer_id, active) values ('043-450-1023', 85, true);
insert into phone (number, customer_id, active) values ('048-650-8848', 52, true);
insert into phone (number, customer_id, active) values ('045-900-7541', 36, true);
insert into phone (number, customer_id, active) values ('042-103-7111', 82, false);
insert into phone (number, customer_id, active) values ('041-898-1163', 80, true);
insert into phone (number, customer_id, active) values ('040-602-1965', 34, false);
insert into phone (number, customer_id, active) values ('043-390-2949', 62, true);
insert into phone (number, customer_id, active) values ('044-430-2155', 47, true);
insert into phone (number, customer_id, active) values ('049-328-7991', 24, false);
insert into phone (number, customer_id, active) values ('042-677-4332', 62, false);
insert into phone (number, customer_id, active) values ('040-966-2232', 85, false);
insert into phone (number, customer_id, active) values ('042-561-9260', 77, true);
insert into phone (number, customer_id, active) values ('048-040-5811', 71, false);
insert into phone (number, customer_id, active) values ('048-218-4684', 67, false);
insert into phone (number, customer_id, active) values ('047-457-4650', 20, true);
insert into phone (number, customer_id, active) values ('042-750-4528', 20, true);
insert into phone (number, customer_id, active) values ('040-307-9424', 39, true);
insert into phone (number, customer_id, active) values ('040-806-8720', 21, true);
insert into phone (number, customer_id, active) values ('043-804-7209', 8, false);
insert into phone (number, customer_id, active) values ('041-298-1272', 76, false);
insert into phone (number, customer_id, active) values ('045-793-5009', 54, false);
insert into phone (number, customer_id, active) values ('049-588-6462', 85, true);
insert into phone (number, customer_id, active) values ('049-056-9404', 54, true);
insert into phone (number, customer_id, active) values ('042-620-5410', 78, false);
insert into phone (number, customer_id, active) values ('042-164-3427', 18, false);
insert into phone (number, customer_id, active) values ('042-085-5470', 60, false);
insert into phone (number, customer_id, active) values ('047-579-5832', 69, false);
insert into phone (number, customer_id, active) values ('044-961-4635', 3, true);
insert into phone (number, customer_id, active) values ('044-368-8365', 61, false);
insert into phone (number, customer_id, active) values ('046-858-9735', 69, false);
insert into phone (number, customer_id, active) values ('042-993-9316', 6, true);
insert into phone (number, customer_id, active) values ('045-618-1837', 51, false);
insert into phone (number, customer_id, active) values ('044-151-2219', 63, false);
insert into phone (number, customer_id, active) values ('045-314-2836', 75, false);
insert into phone (number, customer_id, active) values ('041-127-9198', 84, false);
insert into phone (number, customer_id, active) values ('046-292-9939', 89, true);
insert into phone (number, customer_id, active) values ('042-544-3607', 46, false);
insert into phone (number, customer_id, active) values ('047-749-9702', 56, false);
insert into phone (number, customer_id, active) values ('045-477-1340', 24, false);
insert into phone (number, customer_id, active) values ('049-497-9686', 36, true);
insert into phone (number, customer_id, active) values ('043-351-3382', 75, true);
insert into phone (number, customer_id, active) values ('041-810-9564', 30, false);
insert into phone (number, customer_id, active) values ('041-803-2235', 2, true);
insert into phone (number, customer_id, active) values ('047-645-4995', 100, true);
insert into phone (number, customer_id, active) values ('040-427-9046', 46, false);
insert into phone (number, customer_id, active) values ('042-335-4316', 32, false);
insert into phone (number, customer_id, active) values ('040-460-5373', 34, false);
insert into phone (number, customer_id, active) values ('043-985-1867', 29, true);
insert into phone (number, customer_id, active) values ('046-766-9908', 35, true);
insert into phone (number, customer_id, active) values ('041-425-4225', 61, false);
insert into phone (number, customer_id, active) values ('045-997-0515', 46, false);
insert into phone (number, customer_id, active) values ('048-687-6874', 2, false);
insert into phone (number, customer_id, active) values ('048-086-6186', 84, false);
insert into phone (number, customer_id, active) values ('047-919-4992', 70, true);
insert into phone (number, customer_id, active) values ('048-942-7068', 76, true);
insert into phone (number, customer_id, active) values ('040-722-9987', 66, false);
insert into phone (number, customer_id, active) values ('049-965-2582', 98, true);
insert into phone (number, customer_id, active) values ('040-107-6058', 46, true);
insert into phone (number, customer_id, active) values ('045-898-4431', 97, false);
insert into phone (number, customer_id, active) values ('048-688-8463', 54, true);
insert into phone (number, customer_id, active) values ('046-703-9267', 21, true);
insert into phone (number, customer_id, active) values ('040-202-5614', 79, true);
insert into phone (number, customer_id, active) values ('042-766-0143', 3, true);
insert into phone (number, customer_id, active) values ('047-852-0285', 55, false);
insert into phone (number, customer_id, active) values ('048-481-8603', 68, true);
insert into phone (number, customer_id, active) values ('048-478-6843', 97, true);
insert into phone (number, customer_id, active) values ('040-166-4178', 31, false);
insert into phone (number, customer_id, active) values ('048-243-4917', 72, false);
insert into phone (number, customer_id, active) values ('047-463-6843', 4, false);
insert into phone (number, customer_id, active) values ('045-096-0845', 73, false);
insert into phone (number, customer_id, active) values ('047-843-5311', 7, false);
insert into phone (number, customer_id, active) values ('049-723-8764', 18, true);
insert into phone (number, customer_id, active) values ('045-788-3357', 53, false);
insert into phone (number, customer_id, active) values ('044-123-2545', 89, true);
insert into phone (number, customer_id, active) values ('043-157-2400', 88, false);
insert into phone (number, customer_id, active) values ('040-306-0301', 81, true);
insert into phone (number, customer_id, active) values ('046-963-1572', 35, false);
insert into phone (number, customer_id, active) values ('045-339-3437', 6, false);
insert into phone (number, customer_id, active) values ('041-164-3858', 72, false);
insert into phone (number, customer_id, active) values ('045-990-8481', 65, false);
insert into phone (number, customer_id, active) values ('046-590-1336', 17, true);
insert into phone (number, customer_id, active) values ('040-667-3221', 22, true);
insert into phone (number, customer_id, active) values ('047-054-7477', 73, true);
insert into phone (number, customer_id, active) values ('047-773-6723', 2, false);
insert into phone (number, customer_id, active) values ('040-043-9626', 62, true);
insert into phone (number, customer_id, active) values ('047-827-8572', 67, false);
insert into phone (number, customer_id, active) values ('042-636-4179', 69, false);
insert into phone (number, customer_id, active) values ('041-413-1721', 1, false);
insert into phone (number, customer_id, active) values ('041-919-2278', 56, true);
insert into phone (number, customer_id, active) values ('048-807-9251', 24, true);
insert into phone (number, customer_id, active) values ('043-373-7983', 40, false);
insert into phone (number, customer_id, active) values ('044-012-9463', 46, true);
insert into phone (number, customer_id, active) values ('045-099-9591', 2, false);
insert into phone (number, customer_id, active) values ('048-462-8665', 1, false);
insert into phone (number, customer_id, active) values ('045-206-3465', 86, true);
insert into phone (number, customer_id, active) values ('048-341-8636', 38, true);
insert into phone (number, customer_id, active) values ('043-280-6301', 10, true);
insert into phone (number, customer_id, active) values ('041-308-2122', 47, true);
insert into phone (number, customer_id, active) values ('041-082-8945', 88, false);
insert into phone (number, customer_id, active) values ('040-916-1344', 60, true);
insert into phone (number, customer_id, active) values ('047-102-1156', 80, false);
insert into phone (number, customer_id, active) values ('043-402-4356', 82, false);
insert into phone (number, customer_id, active) values ('048-337-7431', 33, false);
insert into phone (number, customer_id, active) values ('043-837-7724', 95, false);
insert into phone (number, customer_id, active) values ('043-915-9819', 74, false);
insert into phone (number, customer_id, active) values ('041-136-6347', 25, true);
insert into phone (number, customer_id, active) values ('045-073-5613', 89, true);
insert into phone (number, customer_id, active) values ('042-662-7280', 41, false);
insert into phone (number, customer_id, active) values ('044-254-7607', 21, false);
insert into phone (number, customer_id, active) values ('047-890-1296', 15, false);
insert into phone (number, customer_id, active) values ('043-903-9894', 88, false);
insert into phone (number, customer_id, active) values ('040-237-6633', 8, true);
insert into phone (number, customer_id, active) values ('047-937-6399', 59, false);
insert into phone (number, customer_id, active) values ('043-102-6378', 99, false);
insert into phone (number, customer_id, active) values ('042-275-8560', 40, true);
insert into phone (number, customer_id, active) values ('044-237-2657', 76, false);
insert into phone (number, customer_id, active) values ('042-561-2172', 78, false);
insert into phone (number, customer_id, active) values ('047-165-2623', 10, false);
insert into phone (number, customer_id, active) values ('047-339-0444', 37, false);
insert into phone (number, customer_id, active) values ('044-419-5749', 47, false);
insert into phone (number, customer_id, active) values ('042-256-6073', 22, true);
insert into phone (number, customer_id, active) values ('042-776-3144', 85, true);
insert into phone (number, customer_id, active) values ('042-678-1807', 33, false);
insert into phone (number, customer_id, active) values ('044-342-2153', 19, true);
insert into phone (number, customer_id, active) values ('041-342-2551', 55, false);
insert into phone (number, customer_id, active) values ('042-992-1096', 34, false);
insert into phone (number, customer_id, active) values ('041-019-1722', 41, false);
insert into phone (number, customer_id, active) values ('044-029-2666', 60, true);
insert into phone (number, customer_id, active) values ('046-483-9836', 14, true);
insert into phone (number, customer_id, active) values ('047-277-1148', 66, true);
insert into phone (number, customer_id, active) values ('047-565-6961', 14, true);
insert into phone (number, customer_id, active) values ('049-456-7704', 79, true);
insert into phone (number, customer_id, active) values ('040-158-0624', 74, true);
insert into phone (number, customer_id, active) values ('042-682-8961', 97, false);
insert into phone (number, customer_id, active) values ('047-012-7751', 33, false);
insert into phone (number, customer_id, active) values ('047-065-7493', 85, true);
insert into phone (number, customer_id, active) values ('043-914-0585', 21, true);
insert into phone (number, customer_id, active) values ('043-441-3680', 50, true);
insert into phone (number, customer_id, active) values ('045-009-6333', 92, false);
insert into phone (number, customer_id, active) values ('040-622-2348', 78, true);
insert into phone (number, customer_id, active) values ('047-504-2202', 70, false);
  